version: '3.8'
services:
  back-end:
    image: softy-pinko:task4-back-end
    ports:
      - "5252:5252"
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    container_name: back-end

  front-end:
    image: softy-pinko:task4-front-end
    ports:
      - "9000:9000"
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front-end
    depends_on:
      - back-end
